---
repos:
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.27
    hooks:
      - id: conform
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        exclude: .eslintrc.json|node_modules/*
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [
            "--allow-missing-credentials"
        ]
      - id: detect-private-key
        exclude: node_modules/*
#      - id: no-commit-to-branch
#        args: [
#            "--branch",
#            "main",
#            "--branch",
#            "next"
#        ]
